const express = require("express");
const { authenticateToken } = require("../middleware/auth");
const { getSignerWallet, decryptPrivateKey } = require("../utils/walletGenerator");
const { ethers } = require("ethers");
// loading enviornment variables
const router = express.Router();
router.use(authenticateToken);
// taking  the rpc url
const RPC_URL = process.env.RPC_URL || "http://127.0.0.1:8545";

// Load contract addresses (generated by deploy script)
let contractAddresses = {};
try {
  contractAddresses = require("../../frontend/src/config/deployed-addresses.json");
} catch {
  console.warn("⚠️  No deployed-addresses.json found. Blockchain routes will fail until deployment.");
}

// Minimal ABIs for backend signing
const CITIZEN_REGISTRY_ABI = [
  "function registerCitizen(bytes32 zkCommitment, bytes32 mobileHash, uint256 schemeId, uint256[2] a, uint256[2][2] b, uint256[2] c, uint256[1] input) external returns (uint256)"
];

const VENDOR_REGISTRY_ABI = [
  "function registerVendor(uint8 vendorType, string businessName, bytes32 credentialHash, bytes32 bankAccountHash, bytes32 ifscHash) external returns (uint256)"
];