const express = require("express");
const { authenticateToken } = require("../middleware/auth");
const { getSignerWallet, decryptPrivateKey } = require("../utils/walletGenerator");
const { ethers } = require("ethers");
// loading enviornment variables
const router = express.Router();
router.use(authenticateToken);
// taking  the rpc url
const RPC_URL = process.env.RPC_URL || "http://127.0.0.1:8545";

// Load contract addresses (generated by deploy script)
let contractAddresses = {};
try {
  contractAddresses = require("../../frontend/src/config/deployed-addresses.json");
} catch {
  console.warn("⚠️  No deployed-addresses.json found. Blockchain routes will fail until deployment.");
}

// Minimal ABIs for backend signing
const CITIZEN_REGISTRY_ABI = [
  "function registerCitizen(bytes32 zkCommitment, bytes32 mobileHash, uint256 schemeId, uint256[2] a, uint256[2][2] b, uint256[2] c, uint256[1] input) external returns (uint256)"
];

const VENDOR_REGISTRY_ABI = [
  "function registerVendor(uint8 vendorType, string businessName, bytes32 credentialHash, bytes32 bankAccountHash, bytes32 ifscHash) external returns (uint256)"
];
// api for registering citizen on blockchain
router.post("/register-citizen", async (req, res) => {
  const { zkCommitment, mobileHash, schemeId, proof } = req.body;// acccessing data
  const db = req.app.locals.db;

  try {
    const user = await db.prepare("SELECT wallet_private_key_enc, wallet_address FROM users WHERE id = ?").get(req.user.userId);// fetching wallet of user
    if (!user || !user.wallet_private_key_enc) {
      return res.status(400).json({ error: "No wallet generated for this user. Apply for a scheme first." });// if wallet isn't generated then return error
    }
    // creating a signer wallet using private key
    const signer = getSignerWallet(user.wallet_private_key_enc, RPC_URL);
    const citizenReg = new ethers.Contract(
      contractAddresses.CitizenRegistry || ethers.ZeroAddress,
      CITIZEN_REGISTRY_ABI,
      signer
    );
    // calling register citizen
    const tx = await citizenReg.registerCitizen(
      zkCommitment, mobileHash, schemeId,
      proof.a, proof.b, proof.c, proof.input
    );
    const receipt = await tx.wait();// waiting for transaction to be mined
    //  when response == true
    res.json({
      success: true,
      txHash: receipt.hash,
      message: "Citizen registered on-chain (auto-approved)"
    });
  } catch (err) {
    console.error("Blockchain register-citizen error:", err.reason || err.message);
    res.status(500).json({ error: err.reason || err.message || "On-chain registration failed" });
  }
});
// api for registering vendor on blockchain
router.post("/register-vendor", async (req, res) => {
  const { vendorType, businessName, credentialHash, bankAccountHash, ifscHash } = req.body;
  const db = req.app.locals.db;

  try {
    const user = await db.prepare("SELECT wallet_private_key_enc, wallet_address FROM users WHERE id = ?").get(req.user.userId);
    if (!user || !user.wallet_private_key_enc) {
      return res.status(400).json({ error: "No wallet generated for this user." });
    }

    const signer = getSignerWallet(user.wallet_private_key_enc, RPC_URL);
    const vendorReg = new ethers.Contract(
      contractAddresses.VendorRegistry || ethers.ZeroAddress,
      VENDOR_REGISTRY_ABI,
      signer
    );

    const tx = await vendorReg.registerVendor(
      vendorType, businessName, credentialHash, bankAccountHash, ifscHash
    );
    const receipt = await tx.wait();

    res.json({
      success: true,
      txHash: receipt.hash,
      message: "Vendor registered on-chain (pending admin approval)"
    });
  } catch (err) {
    console.error("Blockchain register-vendor error:", err.reason || err.message);
    res.status(500).json({ error: err.reason || err.message || "On-chain registration failed" });
  }
});
// for loading contract addresses freshly to handle redeployments without server restart
router.get("/wallet-info", async (req, res) => {
  const db = req.app.locals.db;
  const user = await db.prepare("SELECT wallet_address, wallet_private_key_enc FROM users WHERE id = ?").get(req.user.userId);

  if (!user || !user.wallet_address) {
    return res.json({ wallet: null, balance: "0", message: "No wallet yet. Apply for a scheme to get one." });
  }

  try {
    const provider = new ethers.JsonRpcProvider(RPC_URL);
    const balance = await provider.getBalance(user.wallet_address);
    
    // Load FRESH contract addresses (not cached) to handle redeployments
    let freshAddresses = {};
    try {
      delete require.cache[require.resolve("../../frontend/src/config/deployed-addresses.json")];
      freshAddresses = require("../../frontend/src/config/deployed-addresses.json");
    } catch {
      try {
        delete require.cache[require.resolve("../../deployed-addresses.json")];
        freshAddresses = require("../../deployed-addresses.json");
      } catch { /* no addresses available */ }
    }

    // Check Digital Rupee token balance
    let tokenBalance = "0";
    if (freshAddresses.DigitalRupee) {
      const dr = new ethers.Contract(
        freshAddresses.DigitalRupee,
        ["function balanceOf(address) view returns (uint256)"],
        provider
      );
      try {
        const bal = await dr.balanceOf(user.wallet_address);
        tokenBalance = ethers.formatEther(bal);
      } catch { /* contract may not be deployed */ }
    }

    res.json({
      wallet: user.wallet_address,
      ethBalance: ethers.formatEther(balance),
      tokenBalance,
      message: "Wallet auto-generated from your identity"
    });
  } catch (err) {
    res.json({ wallet: user.wallet_address, ethBalance: "0", tokenBalance: "0" });
  }
});



