// This file will be auto-populated by the deploy script.
// For local development, run: npx hardhat run scripts/deploy.js --network localhost

// Import addresses if available (generated by deploy script)
// If not deployed yet, all addresses will be empty strings
import addresses from './deployed-addresses.json';



export const CONTRACT_ADDRESSES = {
  DigitalRupee: addresses.DigitalRupee || '',
  ZKVerifier: addresses.ZKVerifier || '',
  TransactionLedger: addresses.TransactionLedger || '',
  CitizenRegistry: addresses.CitizenRegistry || '',
  VendorRegistry: addresses.VendorRegistry || '',
  WelfareScheme: addresses.WelfareScheme || '',
  TokenDistributor: addresses.TokenDistributor || '',
};

// ABIs will be imported from compiled artifacts
// For now, define the essential function signatures
export const ABIS = {
  DigitalRupee: [
    "function name() view returns (string)",
    "function symbol() view returns (string)",
    "function balanceOf(address) view returns (uint256)",
    "function transfer(address to, uint256 amount) returns (bool)",
    "function totalSupply() view returns (uint256)",
    "event TokensMinted(address indexed to, uint256 amount, uint256 timestamp)",
    "event TokensRevoked(address indexed from, uint256 amount, uint256 timestamp)",
    "event Transfer(address indexed from, address indexed to, uint256 value)"
  ],
  CitizenRegistry: [
    "function registerCitizen(bytes32 zkCommitment, bytes32 mobileHash, uint256 schemeId, uint256[2] a, uint256[2][2] b, uint256[2] c, uint256[1] input) returns (uint256)",
    "function getCitizen(uint256 citizenId) view returns (tuple(uint256 id, address walletAddress, bytes32 zkCommitment, uint8 status, uint256 tokenBalance, uint256 registeredAt, uint256 approvedAt, bytes32 mobileHash, uint256 schemeId))",
    "function getCitizenByWallet(address wallet) view returns (tuple(uint256 id, address walletAddress, bytes32 zkCommitment, uint8 status, uint256 tokenBalance, uint256 registeredAt, uint256 approvedAt, bytes32 mobileHash, uint256 schemeId))",
    "function getTotalCitizens() view returns (uint256)",
    "function getApprovedCitizenIds() view returns (uint256[])",
    "event CitizenRegistered(uint256 indexed citizenId, address indexed wallet, bytes32 zkCommitment)",
    "event CitizenApproved(uint256 indexed citizenId, uint256 timestamp)",
    "event CitizenFunded(uint256 indexed citizenId, uint256 amount, uint256 timestamp)"
  ],
  VendorRegistry: [
    "function registerVendor(uint8 vendorType, string businessName, bytes32 credentialHash, bytes32 bankAccountHash, bytes32 ifscHash) returns (uint256)",
    "function isVerifiedVendor(address wallet) view returns (bool)",
    "function getVendor(uint256 vendorId) view returns (tuple(uint256 id, address walletAddress, uint8 vendorType, uint8 status, string businessName, bytes32 credentialHash, bytes32 bankAccountHash, bytes32 ifscHash, uint256 tokenBalance, uint256 exchangedAmount, uint8 exchangeStatus, uint256 exchangeRequestAmount, uint256 registeredAt, uint256 approvedAt, bool rbiTransferConfirmed))",
    "function getVendorByWallet(address wallet) view returns (tuple(uint256 id, address walletAddress, uint8 vendorType, uint8 status, string businessName, bytes32 credentialHash, bytes32 bankAccountHash, bytes32 ifscHash, uint256 tokenBalance, uint256 exchangedAmount, uint8 exchangeStatus, uint256 exchangeRequestAmount, uint256 registeredAt, uint256 approvedAt, bool rbiTransferConfirmed))",
    "function requestExchange(uint256 amount)",
    "function getTotalVendors() view returns (uint256)",
    "function confirmRBITransfer(uint256 vendorId)",
    "event VendorRegistered(uint256 indexed vendorId, address indexed wallet, uint8 vendorType)",
    "event VendorApproved(uint256 indexed vendorId, uint256 timestamp)",
    "event RBITransferConfirmed(uint256 indexed vendorId, uint256 amount, uint256 timestamp)",
    "event TokensRevokedFromVendor(uint256 indexed vendorId, uint256 amount, uint256 timestamp)"
  ],
  WelfareScheme: [
    "function getScheme(uint256 schemeId) view returns (tuple(uint256 id, string name, string description, uint256 totalFund, uint256 distributedFund, uint256 perCitizenAmount, uint8 status, uint256 beneficiaryCount, uint256 createdAt, uint256 updatedAt))",
    "function getTotalSchemes() view returns (uint256)",
    "function getAllSchemeIds() view returns (uint256[])",
    "function getRemainingFund(uint256 schemeId) view returns (uint256)",
    "event SchemeCreated(uint256 indexed schemeId, string name, uint256 totalFund, uint256 perCitizenAmount)"
  ],
  TransactionLedger: [
    "function getPublicTransactions() view returns (tuple(uint256 id, uint8 txType, address from, address to, uint256 amount, uint256 timestamp, string description)[])",
    "function getTotalTransactionCount() view returns (uint256)",
    "function getPrivateTransactionCount() view returns (uint256)",
    "event TransactionLogged(uint256 indexed txId, uint8 indexed txType, address indexed from, address to, uint256 amount, uint256 timestamp)"
  ],
  TokenDistributor: [
    "function manualDistribute()",
    "function manualRevoke()",
    "function getDistributionStatus() view returns (uint256 schemeId, uint256 amount, bool completed)",
    "function configureDistribution(uint256 schemeId, uint256 perCitizenAmount)",
    "event TokensDistributed(uint256 indexed schemeId, uint256 citizenCount, uint256 totalAmount, uint256 timestamp)",
    "event VendorTokensRevoked(uint256 indexed vendorId, address indexed vendorWallet, uint256 amount, uint256 timestamp)"
  ]
};
